
sudo: required
dist: trusty
language: cpp
compiler:
  - clang
before_install:
  - sudo sh -c "echo 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty main' >> /etc/apt/sources.list"
  - sudo apt-get update
  - pip install --user cpp-coveralls

install:
  - sudo apt-get install -y clang-3.8 clang-3.8-doc libclang-common-3.8-dev libclang-3.8-dev libclang1-3.8 libclang1-3.8-dbg libllvm-3.8-ocaml-dev libllvm3.8 libllvm3.8-dbg lldb-3.8 llvm-3.8 llvm-3.8-dev llvm-3.8-doc llvm-3.8-examples llvm-3.8-runtime clang-format-3.8 python-clang-3.8 lldb-3.8-dev liblldb-3.8-dbg

os:
  - linux

branches:
  only:
    - master

script:
    - cmake
    - make clean
    - make all
    - make test

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
