
sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.7
      - clang-3.7-doc
      - libclang-common-3.7-dev
      - libclang-3.7-dev
      - libclang1-3.7
      - libclang1-3.7-dbg
      - libllvm-3.7-ocaml-dev
      - libllvm3.7
      - libllvm3.7-dbg
      - lldb-3.7
      - llvm-3.7
      - llvm-3.7-dev
      - llvm-3.7-doc
      - llvm-3.7-examples
      - llvm-3.7-runtime
      - clang-modernize-3.7
      - clang-format-3.7
      - python-clang-3.7
      - lldb-3.7-dev
      - liblldb-3.7-dbg

os:
  - linux

branches:
  only:
    - master

script: cmake && make clean all test
